### ISSUE TITLE
In the training and testing phases, have Data Augmentation and Self-Ensemble been implemented respectively?

### ISSUE THREAD

**Issue by MoleWei** [zhengchen1999/RGT#12]
I didn't see the option for Self-Ensemble in the testing code, and I haven't looked into whether Data Augmentation has been implemented in the training phase yet.

If it has been implemented, could you please let me know which part of the code it is in? Thank you very much.

**Comment by zhengchen1999** [comment]
The code for Self-Ensemble hasn't been released yet. We will update it soon.

Data Augmentation is used: https://github.com/zhengchen1999/RGT/blob/main/basicsr/data/paired_image_dataset.py#L89

The implementation code: https://github.com/zhengchen1999/RGT/blob/main/basicsr/data/transforms.py#L94

**Comment by MoleWei** [comment]
After thoroughly reviewing the code, I also found the part related to Data-augmentation. Thank you for your response. Looking forward to the official version of self-ensemble.
