### ISSUE TITLE
Image distortion during training

### ISSUE THREAD

**Issue by nldhuyen0047** [zhengchen1999/RGT#17]
Hello, thanks for your excellent work.

I use both DAT2 and RGT for upscaling.

I trained these two models, the datasets I use are cropped images, the scale is 2. LR size: 256x256, HR size: 512x512
When training, with the DAT2 model, when compared with the original HR image, the image is clarified in detail and does not distort the clarified image.
The results with distant objects are not very good or objects such as hair, fur, ..., so I tried with RGT, the results are obviously better, but the image is distorted, the image feels stretched, the distortion is shown in the neighboring pixels.

I don't know if there is any way to improve this. Could you please help me look into this problem?

Thank you very much.

**Comment by zhengchen1999** [comment]
I think this requires a specialized architecture design or targeted dataset fine-tuning. 
Additionally, regarding details like hair and fur, models based on Diffusion Models might produce better results. For example: https://github.com/XPixelGroup/DiffBIR.

**Comment by nldhuyen0047** [comment]
Thanks for you advice.
