### ISSUE TITLE
Name RGTModel is not found, use name: RGTModel_basicsr

### ISSUE THREAD

**Issue by NowLoadY** [zhengchen1999/RGT#5]
hello, I'm trying to run a test on RGT_x4, but after I placed pre-trained in path, and use command "python basicsr/test.py -opt options/test/test_single_x4.yml"
I got:

> Disable distributed.
Path already exists. Rename it to D:\code\python\RGT\results\test_single_x4_archived_20240316_114201
2024-03-16 11:42:01,417 INFO:
  name: test_single_x4
  model_type: RGTModel
  scale: 4
  num_gpu: 1
  manual_seed: 10
  datasets:[
    test_1:[
      name: Single
      type: SingleImageDataset
      dataroot_lq: datasets/single
      io_backend:[
        type: disk
      ]
      phase: test
      scale: 4
    ]
  ]
  network_g:[
    type: RGT
    upscale: 4
    in_chans: 3
    img_size: 64
    img_range: 1.0
    depth: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    resi_connection: 1conv
    split_size: [8, 32]
    c_ratio: 0.5
  ]
  path:[
    pretrain_network_g: experiments/pretrained_models/RGT-S/RGT_S_x4.pth
    strict_load_g: True
    results_root: D:\code\python\RGT\results\test_single_x4
    log: D:\code\python\RGT\results\test_single_x4
    visualization: D:\code\python\RGT\results\test_single_x4\visualization
  ]
  val:[
    save_img: True
    suffix: x4
    use_chop: True
  ]
  dist: False
  rank: 0
  world_size: 1
  auto_resume: False
  is_train: False

> 2024-03-16 11:42:01,418 INFO: Dataset [SingleImageDataset] - Single is built.
2024-03-16 11:42:01,418 INFO: Number of test images in Single: 3
Name RGTModel is not found, use name: RGTModel_basicsr!
Traceback (most recent call last):
  File "basicsr/test.py", line 44, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 34, in test_pipeline
    model = build_model(opt)
  File "D:\app_install_path\miniconda3\envs\detection\lib\site-packages\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "D:\app_install_path\miniconda3\envs\detection\lib\site-packages\basicsr\utils\registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'RGTModel' found in 'model' registry!"

I dont know how to solve it yet, could I get any help?

**Comment by zhengchen1999** [comment]
It seems like the environment hasn't been configured properly. Follow the instructions [here](https://github.com/zhengchen1999/RGT?tab=readme-ov-file#%EF%B8%8F-dependencies) to set up a new environment.
