### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by Qqsoe** [zhengchen1999/RGT#9]
如果我要在一张4090上复现您的论文，需要怎么改动

**Comment by zhengchen1999** [comment]
调整[yml](https://github.com/zhengchen1999/RGT/blob/main/options/train/train_RGT_S_x2.yml#L27)中的batch size（越大越好，不超过显存上限），以及设置`num_gpu: 1`。
使用以下指令：
`python basicsr/train.py -opt options/train/train_RGT_S_x2.yml`

PS：单卡无法完全复现结果，因为4090显存不足以使用batch size=32（4*8）。

**Comment by Qqsoe** [comment]
明白了，感谢您的及时回复
